version: "3"
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=booking
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    container_name: booking-api_mysql
    networks:
      - booking

  php:
    build:
      context: ./
    volumes:
      - .:/app:cached
    working_dir: /app
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://user:password@mysql:3306/booking
    container_name: booking-api_php
    networks:
      - booking

  nginx:
    image: nginx:1.15.8-alpine
    ports:
      - 127.0.0.1:${NGINX_PORT}:80
    volumes:
      - .:/app:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro,cached
    container_name: booking-api_nginx
    networks:
      - booking

networks:
  booking:
    driver: bridge
